# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cqtimes' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod ’AFNetworking'
  pod ’SDWebImage'
  pod ’MJRefresh'
  pod ’MJExtension'
  pod 'IQKeyboardManager'
  pod ‘Masonry’
  pod ‘UITableView+FDTemplateLayoutCell’

end
